version = 1
SPDX-PackageName = "nomos-maths"
SPDX-PackageSupplier = "rodgert@twrodgers.com"
SPDX-PackageDownloadLocation = "https://github.com/nomos-studio/nomos-maths"

[[annotations]]
path = ["src/**", "test/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025-2026 nomos-studio contributors"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = ["project.clj", "scripts/**", ".gitignore"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025-2026 nomos-studio contributors"
SPDX-License-Identifier = "EPL-2.0"
